### ISSUE TITLE
Issue starting on GNU+Linux

### ISSUE THREAD

**Issue by NicolasCARPi** [Guillaume-Levrier/PANDORAE#16] opened 2021-02-06 11:01 UTC
Hello,

It seems I cannot start this on GNU+Linux. I downloaded the archive, extracted it, and ran `./PANDORAE`.

Here is the error message:

~~~
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /home/ktr/PANDORAE-linux-x64/resources/app/node_modules/keytar/build/Release/keytar.node: invalid ELF header
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/ktr/PANDORAE-linux-x64/resources/app/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
~~~

And here is the return of the `file` command on this file:

`resources/app/node_modules/keytar/build/Release/keytar.node: Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK>`

As you can see it's a Mach-O binary, for Mac OS.

**Comment by Guillaume-Levrier** [comment] 2021-02-06 11:04
Thx for the feedback!
Does  the error show when you clone the repo & do npm i -> npm start ?

**Comment by NicolasCARPi** [comment] 2021-02-06 11:07
No, when cloning and installing dependencies with npm it starts. Then I only see a white window but that's another issue ;)

**Comment by Guillaume-Levrier** [comment] 2021-02-06 11:19
Might be the same root cause: keytar not running because it's a native node module, and electron still has issues managing that.

if you do 

`./node_modules/.bin/electron-rebuild`

then

`npm start `

does it work better?

**Comment by NicolasCARPi** [comment] 2021-02-06 11:28
It's still a blank screen, even if it seems that keytar is rebuilt:

![2021-02-06-122721_1025x121_scrot](https://user-images.githubusercontent.com/3043706/107116905-c2e2b880-6876-11eb-8416-b8781ce4a5dc.png)

**Comment by Guillaume-Levrier** [comment] 2021-02-06 11:30
Gotcha. Thanks a lot for trying all this, I will work on packaging a working linux archive and get back to you ASAP!

**Comment by Guillaume-Levrier** [comment] 2021-03-10 12:15
Update: thanks to @Yomguithereal's help, PANDORÆ builds will be issued through GitHub actions. I'm currently working on the electron-builder config, so a working ubuntu version should be out soon.

**Comment by boogheta** [comment] 2022-12-13 16:25
Similar issue:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.DNS66M: en-tÃªte ELF invalide
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/boogheta/Téléchargements/PANDORAE-linux-x64/resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
    at Module
```

**Comment by Guillaume-Levrier** [comment] 2022-12-13 16:32
😭

**Comment by Guillaume-Levrier** [comment] 2023-10-13 11:47
This should be fixed with the new keytarless releases!

**Closed as completed by Guillaume-Levrier** 2023-10-13 11:47 UTC

**Comment by boogheta** [comment] 2023-10-13 14:45
#gg
